version: '3.8'

services:
  # Servicio de la base de datos MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-ia-platform
    environment:
      MYSQL_ROOT_PASSWORD:  # Deja vacío para coincidir con XAMPP
      MYSQL_DATABASE: ia_platform
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Monta tu archivo SQL para inicializar la base de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ia-platform-network

  # Servicio de tu aplicación Spring Boot
  spring-app:
    build: .
    container_name: springboot-ia-platform
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ia_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:  # Debe coincidir con la contraseña de MySQL
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - ia-platform-network

volumes:
  mysql_data:

networks:
  ia-platform-network:
    driver: bridge